[package]
name = "rust_diary"
version = "0.1.0"
edition = "2021"

[dependencies]
diary-core = {path = "../diary-core"}
tokio = { version = "1.28", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"