[package]
name = "rust_diary"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite", "time"] }
anyhow = "1.0"
dotenv = "0.15"